services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - app-data:/app/server/data
      - app-upload-tmp:/app/tmp/config-uploads

volumes:
  app-data:
  app-upload-tmp:
